export interface Alimentador{
    SALIM_CODIGO : string,
    SALIM_NOMBRE : string,
    SALIM_REFERENCIA : string,
    SALIM_PROVINCIA: string,
    SALIM_CANTON: string,
    SALIM_SUBESTACION: string,
    SALIM_SUBADMS: string,
    SALIM_KVA: string,
    SALIM_LINEA: string,
    SALIM_TIPO: string,
    SALIM_OBSERVACION : string,
    SALIM_FECHA : string,
    SALIM_ESTADO : string,
    SALIM_SUBADMS_CAMBIO : string,
    SALIM_NOMBREADMS_CAMBIO : string,
    SALIM_ALIMENTADORID_SIGELEC:string,
    SALIM_SUBESTACIONID_SIGELEC:string,
    SALIM_SUBANTERIOR_CAMBIO:string
}